/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"

#import "MobileCommon.h"

@interface LoginResponse : NSObject <TBase, NSCoding> {
  Response * __response;
  User * __userDetails;
  UserConfig * __userConfig;

  BOOL __response_isset;
  BOOL __userDetails_isset;
  BOOL __userConfig_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=response, setter=setResponse:) Response * response;
@property (nonatomic, retain, getter=userDetails, setter=setUserDetails:) User * userDetails;
@property (nonatomic, retain, getter=userConfig, setter=setUserConfig:) UserConfig * userConfig;
#endif

- (id) init;
- (id) initWithResponse: (Response *) response userDetails: (User *) userDetails userConfig: (UserConfig *) userConfig;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Response *) response;
- (void) setResponse: (Response *) response;
#endif
- (BOOL) responseIsSet;

#if !__has_feature(objc_arc)
- (User *) userDetails;
- (void) setUserDetails: (User *) userDetails;
#endif
- (BOOL) userDetailsIsSet;

#if !__has_feature(objc_arc)
- (UserConfig *) userConfig;
- (void) setUserConfig: (UserConfig *) userConfig;
#endif
- (BOOL) userConfigIsSet;

@end

@protocol MobileAuth <NSObject>
- (LoginResponse *) login: (NSString *) email password: (NSString *) password;  // throws TException
- (LoginResponse *) refresh: (NSString *) email userId: (int32_t) userId tenantId: (int64_t) tenantId userKey: (NSString *) userKey;  // throws TException
@end

@interface MobileAuthClient : NSObject <MobileAuth> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface MobileAuthProcessor : NSObject <TProcessor> {
  id <MobileAuth> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithMobileAuth: (id <MobileAuth>) service;
- (id<MobileAuth>) service;
@end

@interface MobileAuthConstants : NSObject {
}
+ (int32_t) ERROR_SVC;
+ (int32_t) ERROR_AUTHENTICATION_FAILED;
+ (int32_t) ERROR_VALIDATION_EMAIL;
+ (int32_t) ERROR_VALIDATION_PASSWORD;
+ (int32_t) ERROR_VALIDATION_USERID;
+ (int32_t) ERROR_VALIDATION_TENANTID;
+ (int32_t) ERROR_VALIDATION_USERKEY;
+ (int32_t) ERROR_TENANT_INACTIVE;
+ (int32_t) ERROR_USER_INACTIVE;
@end
