pod 'AppSDK', :git => 'https://github.com/PCNguyen/AppSDK.git'
pod 'Mixpanel', '~> 2.3.5'
pod 'AFNetworking'
pod 'PQFCustomLoaders'
pod 'JWGCircleCounter', '~>  0.2.2'
pod 'TTTAttributedLabel', '~> 1.9.5'
pod 'Reachability'
pod 'JNKeychain'